# fly.toml app configuration file generated for uniconnect-dashboard-little-morning-9182 on 2026-05-10T17:22:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uniconnect-dashboard-little-morning-9182'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
